### PR TITLE
Further improve fcall speed

### PR DESCRIPTION
**Pull request by sjinks**

### CODE REVIEW

**Comment by Jurigag** [comment]
This looks like a bit more changes than you wrote in patch, hope it won't break anything and improve speed even more.

**Comment by sjinks** [comment]
:-) I was about to ask you to benchmark this PR

**Comment by Jurigag** [comment]
Well im home already, will check it out tomorrow when will be in work.

**Comment by sjinks** [comment]
I have eliminated zend_string allocation in `zephir_make_fcall_key()` (it is on hot path) and use static buffer instead. *In theory*, this should not break anything as I have not changed any logic.

**Comment by sjinks** [comment]
```
$this->f()         1.809
self::f()          1.917
self::f() -> true  1.931
```

**Comment by sjinks** [comment]
With the latest changes (eliminated one `memcpy`):

```
$this->f()         1.717
self::f()          1.846
self::f() -> true  1.841
```

**Comment by Jurigag** [comment]
Well and orginally without this pr what were your result?

**Comment by sjinks** [comment]
```
$this->f()         2.134
self::f()          2.282
self::f() -> true  2.292
```

**Comment by sjinks** [comment]
~20% faster now

**Comment by Jurigag** [comment]
Well then nice, i will check tomorrow cuz im on other pc without vagrant or docker and would need to install everything and im too lazy for today to do this.

**Comment by Jurigag** [comment]
```
$this->f()         0.635
self::f()          0.739
self::f() -> true  0.746
------------------------
Total              5.285
```

Yea, nice now. Without this:

```
$this->f()         0.731
self::f()          0.827
self::f() -> true  0.924
------------------------
Total              5.917
```

**Comment by sjinks** [comment]
What are your figures for 0.9.6a-dev?

**Comment by Jurigag** [comment]
```
$this->f()         0.260
self::f()          0.266
self::f() -> true  0.262
```

**Comment by sjinks** [comment]
3x difference :-(

**Comment by Jurigag** [comment]
Yea it is :C if you will be able to do anything that it would be great, but still - it's better than before, before. More than 2 weeks ago it was 9x difference.

**Comment by sjinks** [comment]
I had an enlightenment. Could you please test sjinks/zephir@6ad6016?

**Comment by Jurigag** [comment]
```
$this->f()         0.361
self::f()          0.361
self::f() -> true  0.366
```

Such a small change and such a boost ;o

**Pull request merged**
