### PR TITLE
fix incorrect usage of zend_declare_class_constant_ex

### LINKED ISSUE #14160: 3.4.3 segfaults with PHP 7.3.6 (but not 7.3.5) and OPcache
Having cphalcon 3.4.3 enabled in PHP 7.3.6 together with OPcache leads to a segmentation fault somewhere during engine or request shutdown - scripts etc run fine, but PHP segfaults before exiting:

```ShellSession
$ php -v
PHP 7.3.6 (cli) (built: May 30 2019 14:55:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6, Copyright (c) 1999-2018, by Zend Technologies
Segmentation fault
```

Disabling phalcon, or disabling opache, fixes the issue.

The crash does not occur on 7.3.5, which makes me think it's related to OPcache changes in 7.3.6 the changelog describes as "fixed possible crashes, because of inconsistent PCRE cache and opcache SHM reset."

I can't rebuild everything as debug builds at the moment and provide core dumps etc, so I'm hoping y'all can reproduce and diagnose this more easily than me.

### Details

```ShellSession
$ php --ri phalcon

phalcon

Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.4.3
Build Date => Mar  8 2019 15:07:32
Powered by Zephir => Version 0.10.14-975ad02db4

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off
Segmentation fault
```

```ShellSession
$ php -i
phpinfo()
PHP Version => 7.3.6

System => Linux f94a1774-dc9b-47b5-b3bf-6b2007d6deb8 4.4.0-1044-aws #47-Ubuntu SMP Wed May 8 19:02:36 UTC 2019 x86_64
Build Date => May 30 2019 14:52:51
Configure Command =>  './configure'  '--prefix=/app/.heroku/php' '--with-config-file-path=/app/.heroku/php/etc/php' '--with-config-file-scan-dir=/app/.heroku/php/etc/php/conf.d' '--disable-phpdbg' '--enable-fpm' '--with-bz2' '--with-curl' '--with-pdo-mysql' '--with-mysqli' '--with-openssl' '--with-kerberos' '--with-pgsql' '--with-pdo-pgsql' '--with-readline' '--enable-sockets' '--enable-zip' '--with-zlib' '--enable-bcmath=shared' '--enable-calendar=shared' '--enable-exif=shared' '--enable-ftp=shared' '--with-gd=shared' '--with-freetype-dir=/usr' '--with-jpeg-dir=/usr' '--with-png-dir=/usr' '--with-gettext=shared' '--with-gmp=shared' '--with-imap=shared,/app/.heroku/php/opt/imap-2007f' '--with-imap-ssl' '--enable-intl=shared' '--with-ldap=shared' '--with-ldap-sasl' '--enable-mbstring=shared' '--enable-pcntl=shared' '--enable-shmop=shared' '--enable-soap=shared' '--with-sqlite3=shared' '--with-pdo-sqlite=shared' '--with-xmlrpc=shared' '--with-xsl=shared' '--enable-opcache-file' '--without-libzip' '--with-sodium=shared'
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /app/.heroku/php/etc/php
Loaded Configuration File => /app/.heroku/php/etc/php/php.ini
Scan this dir for additional .ini files => /app/.heroku/php/etc/php/conf.d
Additional .ini files parsed => /app/.heroku/php/etc/php/conf.d/000-heroku.ini,
/app/.heroku/php/etc/php/conf.d/010-ext-zend_opcache.ini,
/app/.heroku/php/etc/php/conf.d/100-ext-bcmath.ini,
/app/.heroku/php/etc/php/conf.d/110-ext-calendar.ini,
/app/.heroku/php/etc/php/conf.d/120-ext-intl.ini,
/app/.heroku/php/etc/php/conf.d/130-ext-mbstring.ini,
/app/.heroku/php/etc/php/conf.d/140-ext-xmlrpc.ini,
/app/.heroku/php/etc/php/conf.d/150-ext-phalcon.ini,
/app/.heroku/php/etc/php/conf.d/160-ext-redis.ini
…
Segmentation fault
```

### PR DESCRIPTION
**Pull request by dzuelke**
https://github.com/phalcon/cphalcon/issues/14160
https://bugs.php.net/bug.php?id=78121

Hello!

This fixes https://github.com/phalcon/cphalcon/issues/14160, author attribution is for @krakjoe in the commit.

I haven't touched the changelog yet as I'm not sure what the target version would be? Surely a bugfix release and not the next major version?

PR is editable.

### CODE REVIEW

**Comment by krakjoe** [comment]
The build will fail in 7.1, the string only needs to be interned from 7.2+, the API used doesn't exist in 7.1 ... sorry about that, I wasn't meaning for the patch to be used verbatim, just showing the way ;)

**Comment by krakjoe** [comment]
```diff
diff --git a/ext/kernel/main.c b/ext/kernel/main.c
index c940e0e26..c8d45ce0b 100644
--- a/ext/kernel/main.c
+++ b/ext/kernel/main.c
@@ -387,7 +387,24 @@ zend_class_entry* zephir_get_internal_ce(const char *class_name, unsigned int cl
 /* Declare constants */
 int zephir_declare_class_constant(zend_class_entry *ce, const char *name, size_t name_length, zval *value)
 {
-#if PHP_VERSION_ID >= 70100
+#if PHP_VERSION_ID >= 70200
+       int ret;
+       zend_string *key;
+
+       if (ce->type == ZEND_INTERNAL_CLASS) {
+               key = zend_string_init_interned(name, name_length, 1);
+       } else {
+               key = zend_string_init(name, name_length, 0);
+       }
+
+       zend_declare_class_constant_ex(ce, key, value, ZEND_ACC_PUBLIC, NULL);
+
+       if (ce->type != ZEND_INTERNAL_CLASS) {
+               zend_string_release(key);
+       }
+
+       return ret;
+#elif PHP_VERSION_ID >= 70100
        int ret;
 
        zend_string *key = zend_string_init(name, name_length, ce->type & ZEND_INTERNAL_CLASS);
```

Try that ... (this one can be used verbatim) ...

**Comment by krakjoe** [comment]
I'm confused, we were talking on a cphalcon issue, and now here ... the patch above was made against cphalcon, I can't figure out where to send a full pr, and that doesn't seem to apply here ...

**Comment by dzuelke** [comment]
Zephir is the "framework" with which Phalcon is written; the `ext/kernel/main.c` is vendored in from Zephir, and there the file in turn is generated from `kernels/ZendEngine3/main.c`.

**Comment by krakjoe** [comment]
Oh I see, I opened a pr on both anyway, wanted to see a green build ;)

So, I should close the cphalcon pr ?

**Comment by dzuelke** [comment]
There, @krakjoe, next attempt (diff looks a bit ugly on GitHub).

The important bit is to not edit `ext/kernel/main.c` directly it seems (I'm not a Phalcon user either, just trying to help fix the segfault a customer is having on Heroku).

**Comment by krakjoe** [comment]
ACK, I'll leave you to figure it out, hopefully green now ... @owners,
sorry about the noise ...

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you!

**Pull request merged**
