### PR TITLE
GCC PGO (Profile-guided optimization)

### PR DESCRIPTION
**Pull request by ovr**
Hey!

How to start

Generate gcda profile:

```
cd ext
./pgo-install
```

Start our application 1000 runs
For example

```
./vendor/bin/phpunit - 100 runs :D
```

Next install with `PGO`:

```
cd ext
./pgo-use-install
```
- [X] Added
- [ ] Protect gcda clean

refs @andresgutierrez

### CODE REVIEW

**Comment by ovr** [comment]
ping @andresgutierrez

**Comment by ovr** [comment]
ping @andresgutierrez

**Comment by carvajaldiazeduar** [comment]
I think if `zephir buildpgo`would be available it would be nice

**Comment by phalcon** [comment]
@ovr Can you please built this command directly as a zephyr command?

**Pull request closed without merging**
