### PR TITLE
PHP SDK 2.0 for windows is now hosting on Github

### PR DESCRIPTION
**Pull request by JABirchall**
PHP SDK 2.0 for windows supports php 7.0 and up. While keep backwards compatibility with older versions.
Managed by microsoft.

### CODE REVIEW

**Comment by sergeyklay** [comment]
@JABirchall  We don't add changes directly to stable branches or `master`. Could you please send this PR to the `development` branch?

**Comment by JABirchall** [comment]
Sorry, didnt know, you [CONTRIBUTING.md](https://github.com/phalcon/zephir/blob/master/CONTRIBUTING.md) says to target it to master.

**Comment by sergeyklay** [comment]
Hm.. yes, we should update CONTRIBUTING.md too.

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
