### PR TITLE
Parser, 64bit-portability-issue on openSUSE fix #1162

### LINKED ISSUE #1162: 64bit-portability-issue
I'm trying to build ext with the latest zephir and I'm geting (for both 32/64bit version):

> [  158s] E: php5-phalcon 64bit-portability-issue /home/abuild/rpmbuild/BUILD/php5-phalcon-2.0.10/zephir-master/parser/parser/parser.c:9352

``` log
if (program_length < 2) {
    return SUCCESS;
}
```

### PR DESCRIPTION
**Pull request by mruz**
After this I can build phalcon on openSUSE https://build.opensuse.org/package/show/home:mruz/php5-phalcon

### CODE REVIEW

**Comment by steffengy** [comment]
what is the issue with building on opensuse?

**Comment by mruz** [comment]
As I described in #1162 I think `return SUCCESS;` should be cast to the proper pointer type in `zval *xx_parse_program()` because on the [build.opensuse.org](https://build.opensuse.org/package/show/home:mruz/php5-phalcon) I'm receiving (now it builds because I'm using https://github.com/mruz/zephir):

> [ 158s] E: php5-phalcon 64bit-portability-issue /home/abuild/rpmbuild/BUILD/php5-phalcon-2.0.10/zephir-master/parser/parser/parser.c:9352

Previously it was https://github.com/phalcon/zephir/commit/98e661d67d73a5325ae47b33646911b75d8b61f2#commitcomment-15360283

**Comment by steffengy** [comment]
@mruz 
can you try replacing `unsigned int` with `size_t` in
https://github.com/phalcon/zephir/blob/0e8ebec057045b9b07f27c19c947385174dea73d/parser/parser/base.c#L119
and
https://github.com/phalcon/zephir/blob/c9735cc7ceb1e80908165c3eded57206f5a7319e/parser/zephir_parser.c#L30
?

**Comment by mruz** [comment]
Builds fails https://build.opensuse.org/package/show/home:mruz/php5-phalcon

**Comment by steffengy** [comment]
I think both checks should be merged anyways and return NULL, since else it doesn't really make sense. Then the build should also be fine.

**Comment by mruz** [comment]
Do you mean:

``` c
if (!program_length) {
    return NULL;
}

if (program_length < 2) {
    return NULL;
}
```

?

**Comment by steffengy** [comment]
just

```
if (program_length < 2) {
    return NULL;
}
```

should be enough

**Comment by mruz** [comment]
Yes, builds https://build.opensuse.org/package/show/home:mruz/php5-phalcon are succeeded now.

**Comment by steffengy** [comment]
yeah, can you remove 

```
if (!program_length) {
    return NULL;
}
```

(since that also handled by that case) and squash?

**Comment by mruz** [comment]
Done.

**Comment by mruz** [comment]
If all right, please merge, then I can rebuild packages.

**Comment by steffengy** [comment]
seems fine so far, could you still squash it?
just not a very big fan of polluting the commit history with several reverts of old attempts.

**Comment by mruz** [comment]
Done.

**Pull request merged**
