### PR TITLE
PHP7: Keep in sync with master, fix debug build

### PR DESCRIPTION
**Pull request by steffengy**
Generally ensure that all tests still pass (port scalar optimizer implementation),
and also fix compiling without ZEPHIR_RELEASE, for debugging purposes.

As with last PR, it would be good to wait about a week with the merge,
to minimize the amount of PRs I have to create.

### CODE REVIEW

**Comment by ovr** [comment]
Ping @andresgutierrez 
OMG, Give him write access!

**Comment by andresgutierrez** [comment]
@ovr OMG, and get things merged without reviewing?

**Comment by ovr** [comment]
@andresgutierrez OMG, without your review? Sometime it's needed 1000500 pings(s) to get your attention
You can cancel my contributor access, what is a problem?

```
[22:28:56] Dmitry Patsura: Hey!
[23:21:10] Dmitry Patsura: https://github.com/phalcon/zephir/pull/1053 Can you give him a write access?
[23:21:35] Dmitry Patsura: @steffengy is rly cool guy, and him aimed to help Zephir with PHP 7 support
 пятница, 21 августа 2015 г.
[0:58:10] Andres Gutierrez: he said he doesn’t want him be added as collaborator
 суббота, 22 августа 2015 г.
[20:04:40] Dmitry Patsura: Please give him
[20:04:42] Dmitry Patsura: It's needed
```

How many time is needed to explore you (to give him access)?

10, 100, 1000?)

Like a big* problem to create 2.1.x branch in Phalcon

**Comment by steffengy** [comment]
Just to clarify ``[0:58:10] Andres Gutierrez: he said he doesn’t want him be added as collaborator``,
quote of me from the last PR:
> I also wouldn't mind write access, but that is also no requirement :)

@ovr
First I really appreciate what your trying to do, still
please do not start a "war"/massive conflict because of me :smile:
I'm fine with either situation (direct push to development / indirect via PRs).
Even though I agree that the first would be preferable.

@andresgutierrez 
I honestly do not see why it's such a big deal,
especially all changes (which don't break tests) anyways end up in development 
(except bumping an php (win32) version to ensure tests passing again or something trivial like that).

**Comment by andresgutierrez** [comment]
> Sometime it's needed 1000500 pings(s) to get your attention

You don't have to do that, I'll review things when I have time whatever you ping me or not. I can't understand that anxiety of merge things for versions that aren't soon to be released.

> Like a big\* problem to create 2.1.x branch in Phalcon

For the 70th time, Why do I have to do things just because you want it? 

Regarding copy-paste a private conversation here, It's too unprofessional. 

> You can cancel my contributor access, what is a problem?

I'll do

**Comment by ovr** [comment]
> You don't have to do that, I'll review things when I have time whatever you ping me or not. I can't understand that anxiety of merge things for versions that aren't soon to be released.

Sometimes you are not interested to get attention about PR
You can merge 10 another PRs

But it's not a problem
It takes 1 m to give him write access
but think about this a little be more

@steffengy 
- good developer
- aimed to write PHP7 support

Now @steffengy is working on PHP7 and It's your time to help him with write access, question and etc

Why? Because you are a maintainer

Good maintainer = good manager + good developer
not a good developer + good manager...

> For the 70th time, Why do I have to do things just because you want it?

https://github.com/phalcon/cphalcon/issues/10759
I explain everything about
- Explanation
- Explanation about semver
- 2 big examples about interface BC and why we need to use minnor version not patch

If you are using semver number please obey it
I spent time on it, to explain
It's rly simple to do

```
git checkout -b 2.1.x
git push origin 2.1.x
```

Maybe, you hate me? What is a problem? Say it to me
But create branch if it's needed

And after 1005000 messages you do it, omg, impossible
I will give you :beer: 

> Regarding copy-paste a private conversation here, It's too unprofessional.

So it's an amazing private conversation without any relation about open source project, rly? Maybe it's time for NDA?)

Maybe I am wrong, sorry me

> It's too unprofessional.
> Yeap, but it's not private via I've send this message to get yours attention about this

You ignore me about organization for zephir
If you are interested to be a king of repository

> You can cancel my contributor access, what is a problem?
> I'll do



I will use Zephir organazation

**Comment by steffengy** [comment]
Thinking about the **future of zephir**, since I guess we will see some "splitting" into two/multiple forks, I see several options for me:

## Some options
- **1.** pushing to my branch `ng-refactor2` and `zephir-lang/zephir` (development branch) 
  and still trying to keep `phalcon/zephir` (development) up to date through regular PRs
- **2.** pushing to my branch `ng-refactor2` and `zephir-lang/zephir` and hoping that everything stays in sync/the situation resolves itself
- **3.** pushing gto my branch `ng-refactor2` and keeping `phalcon/zephir` (development) up to date through regular PRs
- **4.** just "maintaining" my branch `ng-refactor2` and not worrying about future trouble/other unprofessional behavior, and just keeping it work for what I need it to do

## General problems despite the choice:
- disparity between the "forks"
- disaster, more work (maybe just as when node/io.js split up and then decided to "merge" again)

## I currently tend to option **2** or **3**.
- **2** is less work for me, but could be negative for the progress of zephir, but generally I like the organization think, since it makes zephir more independent, which also might again have negative consequences regarding the amount of contributions [and unhappy users].
- **3** is more work for me, but might mitigate a bit of this "split up", and might be the more
  stable/futureproof choice? 

## other remarks
- Generally, I'm shocked that such a little detail
  escalated that quickly, due to mistakes/problems on every side.
  I really expected more premediated decisions here...
  I hope that in the end I won't blame myself, that indirectly
  I caused this split up. [which would be stupid of me]

I will have to think about that for a while... 
@ovr @andresgutierrez 
If somebody has some good arguments, please let me know.

**Comment by sergeyklay** [comment]
@andresgutierrez what about this PR?

**Comment by steffengy** [comment]
@sergeyklay 

> As with last PR, it would be good to wait about a week with the merge,
> to minimize the amount of PRs I have to create.

It just was used as a "spam PR" with content not really belonging to the PR,
which is also a bit debatable, but I guess there isn't really another
medium of dev-discussion for zephir.

**Comment by andresgutierrez** [comment]
I don't have password or control over zephir-lang organization. I guess that was created by @ovr. I've asked him several times transfer me the control of that organization but I'm still waiting.

**Comment by Green-Cat** [comment]
@andresgutierrez That is exactly what @steffengy is debating here, the zephir-lang org could serve as a fork of phalcon/zephir, but managed by @ovr. It's just a question of whether @ovr would approve PRs on the zephir-lang/zephir repo. I think that php7 support is a very pressing issue. How fast zephir supports php7 is likely to determine the popularity and future of the zephir project. So I would be strongly in support of whatever means necessary for accomplishing that support faster be it giving @steffengy (who by the way has done remarkable work so far on this) write access to the repo or using the zephir-lang organisation as a fork. I do not think that PRs with a massive number of commits are the most efficient way of accomplishing it though.

Also on the topic, I've had some very simple PRs pending for about 3 weeks now. I have some other CS and other misc improvement PRs lined up, depending on how these ones go, but at this point I am losing hope of anyone ever looking at them.

**Comment by andresgutierrez** [comment]
@Green-Cat Your PRs were submitted to master branch which have code freeze. However, @ovr says that it does not have code freeze because he doesn't agree which sends contradictory messages. Please submit them to development and we're good to go.

If you ask me, just ignore everything under zephir-lang organization as we don't have password or control over it.

**Comment by steffengy** [comment]
@andresgutierrez 
Thanks for providing access now, I also didn't know you had no control over zephir-lang.
With access now, I won't have to choose any of the suboptimal choices, I mentioned above.

I will try to improve ZE3 support even more, if I have time I'll also take a look at improving
building under windows and general refactoring.

If you're fine with it, I also could review/merge PRs into development,
depending on how you want that handled in the future.

**Comment by andresgutierrez** [comment]
@steffengy Thank you, reviewing help in the development branch is more than welcome, keep up the good work

**Comment by Green-Cat** [comment]
@andresgutierrez Okay thanks, I will resubmit them to the development branch.

**Comment by sergeyklay** [comment]
Happy end :)

**Comment by ovr** [comment]
> @Green-Cat Your PRs were submitted to master branch which have code freeze. However, @ovr says that it does not have code freeze because he doesn't agree which sends contradictory messages. Please submit them to development and we're good to go.

So it's impossible to do parallel worflow on 2 branches
See PHP

Master - development
PHP 5.6, 5.5 branches

 With my worflow, it's possible to do minnor and patch releases on master without php 7 support

With your freeze idea it's not possible, and stop stable releases
Because you will w8 `development` as stable, 3-5 month

Maybe it's time for you to read about `git merge` & `git cherry-pick`?

**Comment by andresgutierrez** [comment]
> Because you will w8 development as stable, 3-5 month

Why?

**Comment by ovr** [comment]
@andresgutierrez 
Via PHP7 is not full supported or something can be broken

> 3-5 month
> assumption, I dont know how many time it's needed to develope and test

For example I will do a refactroing an broke something in development

Maybe you would like to say tests, okey
- [ ] Zephir compiler is not tested
- [ ] C output is not tested
- [X] Unit tests on Zephir ext with 20% coverage....

**Comment by andresgutierrez** [comment]
> assumption

Ok, that's an assumption, better

**Pull request merged**
