### PR TITLE
Fixed phalcon usage as module in zephir

### PR DESCRIPTION
**Pull request by mervick**
Fixed usage the external zephir extensions.
Fixed getting/checking methods/properties/constants for the parent classes of external extensions.

fix https://github.com/phalcon/zephir/issues/304
fix https://github.com/phalcon/zephir/issues/1192

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Please don't introduce new static methods, you can use compilation context to pass global state

**Comment by sergeyklay** [comment]
@mervick Could you please fix it?

**Comment by mervick** [comment]
@sergeyklay I guess I can

**Comment by mervick** [comment]
Removed static method, uses compilation context

**Review by sergeyklay — APPROVED** [review]

**Pull request merged**
