### PR TITLE
Add test for #2089

### PR DESCRIPTION
**Pull request by mruz**
Hello!

* Type: bug fix | new feature | code quality | documentation
* Link to issue:

In raising this pull request, I confirm the following:

- [ ] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I updated the CHANGELOG

Small description of change:

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
@mruz Could you please rewrite test case to not use anonymous class (we use PHP 7.0 in tests cases)

**Comment by mruz** [comment]
Ok, but it should be available in PHP 7.0 too.

**Comment by sergeyklay** [comment]
@mruz Also move please this test to file ProtectedPropertiesTest.php

**Comment by sergeyklay** [comment]
@mruz Thank you for the bug report. I'll try to sort out ASAP.

**Pull request closed without merging**
