### PR TITLE
Use local memory management

### PR DESCRIPTION
**Pull request by dreamsxin**
Hello!

* Type: new feature
* Link to issue: #1859 

In raising this pull request, I confirm the following:

- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I updated the CHANGELOG

Small description of change:

Thanks

### CODE REVIEW

**Review by sergeyklay — APPROVED** [review]
:heart:

**Comment by dreamsxin** [comment]
@sergeyklay continuous-integration/appveyor/pr failed

**Comment by dreamsxin** [comment]
Can help fix it and merge @sergeyklay

**Comment by sergeyklay** [comment]
@dreamsxin 
```
C:\projects\zephir\ext\kernel\memory.c(86): error C2373: 'zephir_memory_restore_stack': redefinition; different type modifiers
C:\projects\zephir\ext\kernel/memory.h(66): note: see declaration of 'zephir_memory_restore_stack'
operators.c
require.c
string.c
time.c
```

**Comment by sergeyklay** [comment]
Thank you!

**Pull request merged**
