### PR TITLE
fix global function has not parameter, compile failed

### PR DESCRIPTION
**Pull request by chrysanthemum**
zephir compile:
Error: Call to a member function getParameters() on null in /../zephir/Library/Compiler.php on line 2019

### CODE REVIEW

**Comment by chrysanthemum** [comment]
like this in "fcall.zep" file
```zep
function fun1()  //  has not parameter
{
	echo "someting";
}

class Fcall
{
... 
```

**Comment by sergeyklay** [comment]
@chrysanthemum This PR has conflicts that should be resolved. Could you please rebase?

**Comment by chilimatic** [comment]
shouldn't it be 
```
if ($parameters !== null && count($parameters)) {
```
otherwise you could just use 
```
if ($parameters) {
```
would be less opcode operations and would have the complete same result.

**Comment by chrysanthemum** [comment]
@sergeyklay thinks for your help!  is it correct now?

**Comment by chrysanthemum** [comment]
@chilimatic I was almost mistaken by you. $parameters->getParameters() Be sure to execute this method.

**Comment by chilimatic** [comment]
@chrysanthemum sorry I assumed an overloaded array. I will make sure to read up next time :)

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
