### PR TITLE
Introduced HashEqualsOptimizer

### PR DESCRIPTION
**Pull request by sergeyklay**
This PR introduces the `hash_equals` support/optimizer for PHP >= 5.4.
[Original function](http://php.net/manual/en/function.hash-equals.php) work only for for PHP >= 5.6.

Refs: https://github.com/phalcon/cphalcon/issues/12418

### CODE REVIEW

**Comment by kristoffer-ingemansson** [comment]
Should indent_style really be changed from 'space' to 'tab'?

**Comment by sergeyklay** [comment]
Yes as I see all zep files use tabs instead spaces, but editorconfig uses spaces instead tabs.

**Comment by kristoffer-ingemansson** [comment]
Ok! I thought the space-indentation from the PSR-2 coding style recommendation in zephir/CONTRIBUTING.md also affected zep-files.

**Comment by sergeyklay** [comment]
PSR-2 relate only to the PHP

**Pull request merged**
