### PR TITLE
Fixes bug not resolve constant from interface

### PR DESCRIPTION
**Pull request by KorsaR-ZN**
see #897

### CODE REVIEW

**Comment by steffengy** [comment]
@KorsaR-ZN
Seems fine on the first look.
Could you provide a small test case, to show that the bug is resolved and prevent it from reappearing?

**Comment by KorsaR-ZN** [comment]
@steffengy added tests

**Comment by steffengy** [comment]
Thank you!

**Comment by sergeyklay** [comment]
:+1:

**Pull request merged**
