### PR TITLE
Updated zephir_update_static_property_ce

### PR DESCRIPTION
**Pull request by dreamsxin**
Hello!

* Type: bug fix
* Link to issue: https://github.com/phalcon/zephir/issues/1904

In raising this pull request, I confirm the following:

- [ ] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I updated the CHANGELOG

Small description of change:

Thanks

### CODE REVIEW

**Comment by dreamsxin** [comment]
@sergeyklay Test again

**Comment by sergeyklay** [comment]
```bash
$ cat manual.php
```
```php
<?php

$di = new Phalcon\Di;
```

```bash
$ gdb --args $(phpenv which php) -d extension=ext/modules/phalcon.so manual.php <<EOF
run
bt full
quit
EOF
```

```
#0  0x0000555555e88fd1 in zval_delref_p (pz=0x555556ce90b8) at /home/klay/src/php/source/7.2.20/Zend/zend_types.h:897
        __PRETTY_FUNCTION__ = "zval_delref_p"
#1  0x0000555555e8cf09 in _zval_internal_ptr_dtor (zval_ptr=0x555556ce90b8, __zend_filename=0x55555674d1d0 "/home/klay/src/php/source/7.2.20/Zend/zend_variables.c", __zend_lineno=126) at /home/klay/src/php/source/7.2.20/Zend/zend_execute_API.c:540
No locals.
#2  0x0000555555ea595c in _zval_internal_dtor_for_ptr (zvalue=0x555556d613d0, __zend_filename=0x55555674a368 "/home/klay/src/php/source/7.2.20/Zend/zend_execute_API.c", __zend_lineno=542) at /home/klay/src/php/source/7.2.20/Zend/zend_variables.c:126
        ref = 0x555556ce90b0
#3  0x0000555555e8cf31 in _zval_internal_ptr_dtor (zval_ptr=0x555556d613d0, __zend_filename=0x55555674bad8 "/home/klay/src/php/source/7.2.20/Zend/zend_opcode.c", __zend_lineno=328) at /home/klay/src/php/source/7.2.20/Zend/zend_execute_API.c:542
No locals.
#4  0x0000555555e937fc in destroy_zend_class (zv=0x555556ee6ed0) at /home/klay/src/php/source/7.2.20/Zend/zend_opcode.c:328
        p = 0x555556d613d0
        end = 0x555556d613e0
        prop_info = 0x555556ecd240
        ce = 0x555556d60f50
#5  0x0000555555ec1d46 in zend_hash_destroy (ht=0x5555569b3d20) at /home/klay/src/php/source/7.2.20/Zend/zend_hash.c:1236
        p = 0x555556ee6ed0
        end = 0x555556ee8e50
        __PRETTY_FUNCTION__ = "zend_hash_destroy"
#6  0x0000555555ea7d28 in compiler_globals_dtor (compiler_globals=0x5555569b3ab0) at /home/klay/src/php/source/7.2.20/Zend/zend.c:593
No locals.
#7  0x0000555555de1cad in tsrm_shutdown () at /home/klay/src/php/source/7.2.20/TSRM/TSRM.c:199
        j = 7
        p = 0x5555569b0010
        next_p = 0x0
        i = 0
#8  0x0000555555fa7570 in main (argc=4, argv=0x5555569aff10) at /home/klay/src/php/source/7.2.20/sapi/cli/php_cli.c:1424
        c = -1
        exit_status = 0
        module_started = 1
        sapi_started = 1
        php_optarg = 0x5555569aff80 "extension=ext/modules/phalcon.so"
        php_optind = 3
        use_extended_info = 0
        ini_path_override = 0x0
        ini_entries = 0x5555569b1140 ""
        ini_entries_len = 143
        ini_ignore = 0
        sapi_module = 0x55555695ca00 <cli_sapi_module>
```

**Comment by sergeyklay** [comment]
Actually it's somehow works:
```c
int zephir_update_static_property_ce(zend_class_entry *ce, const char *property_name, uint32_t property_length, zval *value)
{
#if PHP_VERSION_ID < 70300
	zval *property = zend_read_static_property(ce, property_name, property_length, (zend_bool) ZEND_FETCH_CLASS_SILENT);

	if (!property) {
		return FAILURE;
	}

	if (property == value) {
		return SUCCESS;
	}

	if (Z_ISREF_P(property)) {
		fprintf(stderr, "[%s:%d] property is referenced\n", __func__, __LINE__);
		zval garbage;

		fprintf(stderr, "[%s:%d] trying to deref property\n", __func__, __LINE__);
		ZVAL_DEREF(property);

		fprintf(stderr, "[%s:%d] copy property value to garbage\n", __func__, __LINE__);
		ZVAL_COPY_VALUE(&garbage, property);

		fprintf(stderr, "[%s:%d] dtor garbage\n", __func__, __LINE__);
		zval_dtor(&garbage);

		fprintf(stderr, "[%s:%d] copy value to property\n", __func__, __LINE__);
		ZVAL_COPY_VALUE(property, value);

		fprintf(stderr, "[%s:%d] DONE\n", __func__, __LINE__);
	} else {
		zval_ptr_dtor(property);
		ZVAL_COPY(property, value);
	}

	return SUCCESS;
#else
	return zend_update_static_property(ce, property_name, property_length, value);
#endif
}
```

```bash
$ php -d extension=ext/modules/phalcon.so manual.php
[zephir_update_static_property_ce:1038] property is referenced
[zephir_update_static_property_ce:1041] trying to deref property
[zephir_update_static_property_ce:1044] copy property value to garbage
[zephir_update_static_property_ce:1047] dtor garbage
[zephir_update_static_property_ce:1050] copy value to property
[zephir_update_static_property_ce:1053] DONE

[1]    3535 segmentation fault  php -d extension=ext/modules/phalcon.so manual.php
```

**Comment by dreamsxin** [comment]
Try ZVAL_COPY_VALUE(property, value)； Change to ZVAL_COPY(property, value);

**Comment by sergeyklay** [comment]
@dreamsxin 
```diff
diff --git a/kernels/ZendEngine3/object.c b/kernels/ZendEngine3/object.c
index a9842e6c..15c37f02 100644
--- a/kernels/ZendEngine3/object.c
+++ b/kernels/ZendEngine3/object.c
@@ -1031,7 +1031,7 @@ int zephir_update_static_property_ce(zend_class_entry *ce, const char *property_
                        ZVAL_DEREF(property);
                        ZVAL_COPY_VALUE(&garbage, property);
                        zval_dtor(&garbage);
-                       ZVAL_COPY_VALUE(property, value);
+                        ZVAL_COPY(property, value);
                } else {
                        zval_ptr_dtor(property);
                        ZVAL_COPY(property, value);
```

```sh
php -d extension=ext/modules/phalcon.so manual.php
```

```
[Sun Oct  6 20:00:03 2019]  Script:  '/mnt/work/phalcon/cphalcon/manual.php'
/home/klay/src/php/source/7.2.20/Zend/zend_objects.c(161) :  Freeing 0x00007f981b682080 (88 bytes), script=/mnt/work/phalcon/cphalcon/manual.php
=== Total 1 memory leaks detected ===
[1]    17129 segmentation fault  php -d extension=ext/modules/phalcon.so manual.php
```

```
#0  0x0000555555e88fd1 in zval_delref_p (pz=0x555556ce8fb8) at /home/klay/src/php/source/7.2.20/Zend/zend_types.h:897
        __PRETTY_FUNCTION__ = "zval_delref_p"
#1  0x0000555555e8cf09 in _zval_internal_ptr_dtor (zval_ptr=0x555556ce8fb8, __zend_filename=0x55555674d1d0 "/home/klay/src/php/source/7.2.20/Zend/zend_variables.c", __zend_lineno=126) at /home/klay/src/php/source/7.2.20/Zend/zend_execute_API.c:540
No locals.
#2  0x0000555555ea595c in _zval_internal_dtor_for_ptr (zvalue=0x555556d612d0, __zend_filename=0x55555674a368 "/home/klay/src/php/source/7.2.20/Zend/zend_execute_API.c", __zend_lineno=542) at /home/klay/src/php/source/7.2.20/Zend/zend_variables.c:126
        ref = 0x555556ce8fb0
#3  0x0000555555e8cf31 in _zval_internal_ptr_dtor (zval_ptr=0x555556d612d0, __zend_filename=0x55555674bad8 "/home/klay/src/php/source/7.2.20/Zend/zend_opcode.c", __zend_lineno=328) at /home/klay/src/php/source/7.2.20/Zend/zend_execute_API.c:542
No locals.
#4  0x0000555555e937fc in destroy_zend_class (zv=0x555556ee6dd0) at /home/klay/src/php/source/7.2.20/Zend/zend_opcode.c:328
        p = 0x555556d612d0
        end = 0x555556d612e0
        prop_info = 0x555556ecd140
        ce = 0x555556d60e50
#5  0x0000555555ec1d46 in zend_hash_destroy (ht=0x5555569b3a90) at /home/klay/src/php/source/7.2.20/Zend/zend_hash.c:1236
        p = 0x555556ee6dd0
        end = 0x555556ee8d50
        __PRETTY_FUNCTION__ = "zend_hash_destroy"
#6  0x0000555555ea7d28 in compiler_globals_dtor (compiler_globals=0x5555569b3820) at /home/klay/src/php/source/7.2.20/Zend/zend.c:593
No locals.
#7  0x0000555555de1cad in tsrm_shutdown () at /home/klay/src/php/source/7.2.20/TSRM/TSRM.c:199
        j = 7
        p = 0x5555569afd80
        next_p = 0x0
        i = 0
#8  0x0000555555fa7570 in main (argc=4, argv=0x5555569afc80) at /home/klay/src/php/source/7.2.20/sapi/cli/php_cli.c:1424
        c = -1
        exit_status = 0
        module_started = 1
        sapi_started = 1
        php_optarg = 0x5555569afcf0 "extension=ext/modules/phalcon.so"
        php_optind = 3
        use_extended_info = 0
        ini_path_override = 0x0
        ini_entries = 0x5555569b0eb0 ""
        ini_entries_len = 143
        ini_ignore = 0
        sapi_module = 0x55555695ca00 <cli_sapi_module>
```

**Comment by dreamsxin** [comment]
@sergeyklay 
I tested it again and it turned out to be correct.
```php
<?php
$di = new Phalcon\Di;
```
```c
int zephir_update_static_property_ce(zend_class_entry *ce, const char *property_name, uint32_t property_length, zval *value)
{
#if PHP_VERSION_ID < 70300
	zval *property, garbage;
	property = zend_read_static_property(ce, property_name, property_length, (zend_bool)ZEND_FETCH_CLASS_SILENT);
	if (property && property != value) {
		if (Z_ISREF_P(property)) {
			ZVAL_DEREF(property);
			ZVAL_COPY_VALUE(&garbage, property);
			zval_dtor(&garbage);
			ZVAL_COPY_VALUE(property, value);
		} else {
			zval_ptr_dtor(property);
			ZVAL_COPY(property, value);
		}
		return 1;
	}
#else
	zend_update_static_property(ce, property_name, property_length, value);
#endif
}
```

**Comment by sergeyklay** [comment]
@dreamsxin Take a look at https://travis-ci.org/phalcon/cphalcon/builds/594431268
Its your repo and branch

**Comment by dreamsxin** [comment]
@sergeyklay 

Test again, If I fail, I will give  up.

**Comment by sergeyklay** [comment]
```
#0  0x0000555555e88fd1 in zval_delref_p (pz=0x555556ce9138) at /home/klay/src/php/source/7.2.20/Zend/zend_types.h:897
        __PRETTY_FUNCTION__ = "zval_delref_p"
#1  0x0000555555e8cf09 in _zval_internal_ptr_dtor (zval_ptr=0x555556ce9138, __zend_filename=0x55555674d1d0 "/home/klay/src/php/source/7.2.20/Zend/zend_variables.c", __zend_lineno=126) at /home/klay/src/php/source/7.2.20/Zend/zend_execute_API.c:540
No locals.
#2  0x0000555555ea595c in _zval_internal_dtor_for_ptr (zvalue=0x555556d61450, __zend_filename=0x55555674a368 "/home/klay/src/php/source/7.2.20/Zend/zend_execute_API.c", __zend_lineno=542) at /home/klay/src/php/source/7.2.20/Zend/zend_variables.c:126
        ref = 0x555556ce9130
#3  0x0000555555e8cf31 in _zval_internal_ptr_dtor (zval_ptr=0x555556d61450, __zend_filename=0x55555674bad8 "/home/klay/src/php/source/7.2.20/Zend/zend_opcode.c", __zend_lineno=328) at /home/klay/src/php/source/7.2.20/Zend/zend_execute_API.c:542
No locals.
#4  0x0000555555e937fc in destroy_zend_class (zv=0x555556ee6f50) at /home/klay/src/php/source/7.2.20/Zend/zend_opcode.c:328
        p = 0x555556d61450
        end = 0x555556d61460
        prop_info = 0x555556ecd2c0
        ce = 0x555556d60fd0
#5  0x0000555555ec1d46 in zend_hash_destroy (ht=0x5555569b3b20) at /home/klay/src/php/source/7.2.20/Zend/zend_hash.c:1236
        p = 0x555556ee6f50
        end = 0x555556ee8ed0
        __PRETTY_FUNCTION__ = "zend_hash_destroy"
#6  0x0000555555ea7d28 in compiler_globals_dtor (compiler_globals=0x5555569b38b0) at /home/klay/src/php/source/7.2.20/Zend/zend.c:593
No locals.
#7  0x0000555555de1cad in tsrm_shutdown () at /home/klay/src/php/source/7.2.20/TSRM/TSRM.c:199
        j = 7
        p = 0x5555569afe10
        next_p = 0x0
        i = 0
#8  0x0000555555fa7570 in main (argc=4, argv=0x5555569afd10) at /home/klay/src/php/source/7.2.20/sapi/cli/php_cli.c:1424
        c = -1
        exit_status = 0
        module_started = 1
        sapi_started = 1
        php_optarg = 0x5555569afd80 "extension=ext/modules/phalcon.so"
        php_optind = 3
        use_extended_info = 0
        ini_path_override = 0x0
        ini_entries = 0x5555569b0f40 ""
        ini_entries_len = 143
        ini_ignore = 0
        sapi_module = 0x55555695ca00 <cli_sapi_module>
```

**Comment by sergeyklay** [comment]
@sjinks Could you help us by any chance? 🙏

**Comment by sergeyklay** [comment]
The main problem is `ZVAL_DEREF(property);`. Commenting this fixes segfault in phalcon but then this test fails
```php
        \Test\Properties\StaticPublicProperties::setSomeString('test3');
        $this->assertSame(\Test\Properties\StaticPublicProperties::$someString, $value);
```

**Comment by dreamsxin** [comment]
@sergeyklay 

If you do not dereference manually, the reference will be destroyed.

use ZVAL_COPY or ZVAL_DUP
```c
		if (Z_ISREF_P(property)) {
			...
			ZVAL_COPY(property, value);
		}
```
PHP < 7.3, will output "Internal zval's can't be arrays, objects or resources"
```c
ZEND_API void _zval_internal_dtor_for_ptr(zval *zvalue ZEND_FILE_LINE_DC)
{
	switch (Z_TYPE_P(zvalue)) {
		case IS_STRING:
		case IS_CONSTANT:
			CHECK_ZVAL_STRING_REL(Z_STR_P(zvalue));
			zend_string_free(Z_STR_P(zvalue));
			break;
		case IS_ARRAY:
		case IS_CONSTANT_AST:
		case IS_OBJECT:
		case IS_RESOURCE:
			zend_error_noreturn(E_CORE_ERROR, "Internal zval's can't be arrays, objects or resources");
			break;
		
```
But with zval_copy_alue, the reference count is not correct.

**Comment by Jeckerson** [comment]
Closing due legacy versions support...

**Pull request closed without merging**
