### PR TITLE
Fixed API geneneration

### PR DESCRIPTION
**Pull request by sergeyklay**

### CODE REVIEW

**Comment by sergeyklay** [comment]
**Before:**
api_1

**After:**
api_3

**Comment by sergeyklay** [comment]
@steffengy Can you please review this?

**Comment by carvajaldiazeduar** [comment]
+1

**Comment by sergeyklay** [comment]
**Before:**
api_1 2

**After:**
api_3 2

**Comment by sergeyklay** [comment]
I've created a demo with these changes: http://phalcon-api.klay.me/

**Comment by mruz** [comment]
Also you can add docblock for classes https://github.com/phalcon/zephir/pull/724#issuecomment-122554227 and try to sort classes/namespaces by name on the list.

**Comment by sergeyklay** [comment]
@steffengy What with this PR?

**Comment by steffengy** [comment]
sorry, seems like I missed that one because of the failing PHP7 tests during that time.

**Pull request merged**
