### PR TITLE
Test globals

### PR DESCRIPTION
**Pull request by Jurigag**

### CODE REVIEW

**Comment by Jurigag** [comment]
Any idea why globals_set not working? @sergeyklay @sjinks

**Comment by sergeyklay** [comment]
I'll try to sort out

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.

**Comment by Jurigag** [comment]
Oh nice, that's good that it's solved finally.

**Pull request closed without merging**
