### PR TITLE
Fixed backwards compatibility for zephir_camelize

### PR DESCRIPTION
**Pull request by sergeyklay**
refs #1252, https://github.com/phalcon/cphalcon/issues/11767

### CODE REVIEW

**Comment by sergeyklay** [comment]
@steffengy Could you please take a look

**Comment by mdular** [comment]
+2 for speed :)

**Comment by steffengy** [comment]
@sergeyklay 
tests don't seem to pass.
I somehow do not quite like it in terms of coding style, but I think it cannot really
be improved in terms of easily finding a nicer way to "write it down".

**Comment by sergeyklay** [comment]
@steffengy Sorry, it is my typo (missed semicolon). I've fixed the PR.

Yes, I totally agree with you about the coding style, but I think it's the most painless way to restore the old behavior.

**Comment by steffengy** [comment]
@sergeyklay 
What do you think of turning the delimiter parameter to a character mask as in `ltrim`?
This essentially would be using a `char *` with the default value of `-_`.
I think that'd be the cleanest solution and actually not hard to refactor.

If you don't want to do it that way yet, you can merge this to fix the upstream breakage
and please file a new issue :)

**Comment by sergeyklay** [comment]
@steffengy Ok. I hope now is more appropriate. Could you please review?

**Comment by steffengy** [comment]
@sergeyklay 
Yeah thanks for that, I'm stil not sure if I should merge your changes with my rewrite,
since that code seems a lot clearer to me.
https://github.com/steffengy/zephir/commit/f50e6b75c028d6de3cf5cd6289ae298e650a3e36
What do you think?

**Comment by sergeyklay** [comment]
@steffengy I think your changes again will break backwards compatibility because actually `zephir_camelise` didn't normalize string, as you do

**Comment by sergeyklay** [comment]
@steffengy What happened with Appveyor?

**Comment by steffengy** [comment]
@sergeyklay 
seems like a connection-drop to github.

The only thing that actually changes is that something like `__test` wouldn't get transformed to `_test` but to `Test`, which is actually what you'd expect.

Is there anything in phalcon relying on the old malicious behavior in these rare cases?

**Comment by sergeyklay** [comment]
@steffengy No, actually nothing in phalcon not rely on this behavior. But we have public api here https://github.com/phalcon/cphalcon/blob/master/phalcon/text.zep#L47

**Comment by sergeyklay** [comment]
@steffengy Well, I like your solution :) What solution do you think should be merged?

**Comment by virgofx** [comment]
My personal opinion is that the character mask is more appropriate than the `alt` variable, provided that `strchr` is fast enough to not impact performance.

Also can we update the public API on the `Phalcon\Text` to include the extra parameters in docblock?

**Comment by steffengy** [comment]
@sergeyklay I'll take a look at how much relies on that and will discuss with @andresgutierrez soon.

**Comment by sergeyklay** [comment]
@virgofx Yes. We'll do it

**Comment by sergeyklay** [comment]
@steffengy What do you think #1090

**Comment by steffengy** [comment]
@sergeyklay 
What is with #1090, does by any chance your or my solution fix that (or is it already fixed)?
Andres seems to have tagged 0.9.2 now, so that we can decide for either solution,
so we should choose the "most-working" one.

**Comment by sergeyklay** [comment]
@steffengy Yeah, creating the 0.9.2 tag a great solution that allows to return the old behavior. Indeed, we can now choose the best solution. It seems to me the #1090 can be fixed by removing https://github.com/sergeyklay/zephir/blob/3b2a283d881ca811f1717ef09ddf8a2412c3b89b/kernels/ZendEngine2/string.c#L304

**Comment by steffengy** [comment]
@sergeyklay 
that line is surely elementary.
have you checked if my rewritten solution works for that?

**Comment by sergeyklay** [comment]
@steffengy No, if you are talking about concrete testing, I didn't do it. But at first glance looks good to me. You can get current (un)camelize tests and run them

**Pull request closed without merging**
