### PR TITLE
Support for php8

### PR DESCRIPTION
**Pull request by dreamsxin**
Hello!

* Type: new feature
* Link to issue: https://github.com/phalcon/zephir/issues/2111

In raising this pull request, I confirm the following:

- [ ] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I updated the CHANGELOG

Small description of change:

Thanks

### CODE REVIEW

**Review by ruudboon — APPROVED** [review]
LGTM

**Comment by mruz** [comment]
@dreamsxin do you know why builds failed? Could you add php8 to the builds:
https://github.com/phalcon/zephir/blob/fa39eecad8f873a95dbfff9a7120a4483a711be6/.github/workflows/build-unix.yml#L29-L33

Don't forget to update requirement on composer:
https://github.com/phalcon/zephir/blob/fa39eecad8f873a95dbfff9a7120a4483a711be6/composer.json#L24

**Comment by dreamsxin** [comment]
@mruz When php8 is released, I will update it again and fix it
```text
# passed all 2 test(s)
1..2
./t0002-generate.sh
not ok 1 - Should correctly specify ARGINFO
#	
#	  cd /home/runner/work/zephir/zephir/tests/fixtures/typehints &&
#	  zephirc fullclean 2>&1 >/dev/null &&
#	  zephirc generate --backend=ZendEngine3 2>&1 >/dev/null &&
#	  test_cmp ext/typehints.c expected3.c &&
#	  test_cmp ext/typehints/args.zep.h expected_args3.h &&
#	  test_cmp ext/typehints/retval.zep.h expected_retval3.h &&
#	  test_cmp ext/typehints/both.zep.h expected_both3.h
#	
not ok 2 - Life Cycle Test
#	
#	  cd /home/runner/work/zephir/zephir/tests/fixtures/lifecycle &&
#	  zephirc fullclean 2>&1 >/dev/null &&
#	  zephirc generate --backend=ZendEngine3 2>&1 >/dev/null &&
#	  test_cmp ext/lifecycle.c expected3.c
#	
ok 3 - Should generate valid code with inheritance of prototype interfaces
# failed 2 among 3 test(s)
make: *** [t0002-generate.sh] Error 1
1..3
Makefile:39: recipe for target 't0002-generate.sh' failed
Error: Process completed with exit code 2.
```

**Comment by mruz** [comment]
OK, thanks. If you find time, you could try even before the release:
> Specifying 8.0 in php-version input installs a nightly build of PHP 8.0.0-dev
https://github.com/marketplace/actions/setup-php-action#tada-php-support

**Comment by mruz** [comment]
@sergeyklay @niden Can you release a new version of https://github.com/phalcon/php-zephir-parser, please? 
then @dreamsxin can you update it here:
https://github.com/phalcon/zephir/blob/7e827f61ba3f56b482da838c086a81de23df4db1/.github/workflows/build-unix.yml#L14

**Comment by mruz** [comment]
PHP 8.0 has been released. @dreamsxin can you try zephir parser 1.3.5, please? @AlexNDRmac released a new version

**Comment by Jeckerson** [comment]
@mruz wait until next release, as @AlexNDRmac forgot support for windows.

**Comment by AlexNDRmac** [comment]
> @mruz wait until next release, as @AlexNDRmac forgot support for windows.

I'l fix missed windows build and update current parser release. Nothing changed, just one missed appveyour build for win :)

**Comment by AlexNDRmac** [comment]
@dreamsxin - parser now supports PHP 8 and builds for Windows. You can use it - v1.3.6

**Comment by mruz** [comment]
I'm curious if the changes are enough, or if there is still some work to be done. If it's allowed, then any member of the team can push to the fork, @AlexNDRmac maybe you could try to update parser version and see if the build will pass
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by Jeckerson** [comment]
All changes are already inside this branch - https://github.com/phalcon/zephir/tree/zephir-php8

Closing.

@dreamsxin If you could help, there are several bugs still remaining:
* code execution inside `eval()`
* memory leak in method inheritance
https://github.com/phalcon/zephir/blob/0803c0a7fbf478df3f262f34037a2646075551ab/tests/Extension/Oo/ExtendClassTest.php#L68

**Comment by dreamsxin** [comment]
@Jeckerson I didn't find any problems in the test

`Stub\Oo\ConcreteStatic::childFunction();`
out:
```txt
Warning: Invalid callback , no array or string given in work/test.php on line 3

Fatal error: Uncaught RuntimeException: Call to undefined method self::parentfunction() in /home/server/work/test.php:3
Stack trace:
#0 /home/server/work/test.php(3): Stub\Oo\ConcreteStatic::childFunction()
#1 {main}
  thrown in /home/server/work/test.php on line 3
```
`echo (new Stub\EvalTest)->evalCode('return 111;')+1;`
out: `112`

**Comment by Jeckerson** [comment]
@dreamsxin `eval` problem already was fixed. Run all tests to checkout the problems. https://github.com/phalcon/zephir/tree/zephir-php8

**Pull request closed without merging**
