### PR TITLE
Fix #1751 add context in class CompilerFileAnonymous

### LINKED ISSUE #1751: Anonymous function
```zep

namespace Work\Abc;

use Work\Task\Timer;

class Test {


    public function a()
    {
        var result;

	Timer::start(function () {

            let result = Timer::wait();

         });	
     }
}
```
[ERROR] Class name: Work\Timer does not exist in `let result = Timer::wait();`

### PR DESCRIPTION
**Pull request by dreamsxin**

### CODE REVIEW

**Comment by dreamsxin** [comment]
@sergeyklay

**Comment by sergeyklay** [comment]
Could you take a look at Travis build. There is few places you should fix

**Comment by dreamsxin** [comment]
@sergeyklay It's Ok

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
