### PR TITLE
Windows PHPIZE path issues resolved

### PR DESCRIPTION
**Pull request by umermalik129**

### CODE REVIEW

**Comment by steffengy** [comment]
@umermalik129 doesn't seem to work, tests (appveyor) are failing.

**Comment by umermalik129** [comment]
@steffengy where code is breaking? I will try to fix it

**Comment by steffengy** [comment]
https://ci.appveyor.com/project/phalcon/zephir/build/1.0.628

**Comment by umermalik129** [comment]
@steffengy what is this fatal error? "Fatal error: Class 'Test\Arithmetic' not found in C:\projects\zephir\unit-tests\Extension\ArithmeticTest.php on line 28"

**Comment by steffengy** [comment]
I think you should probably take a look at the context (it just means it couldnt load the DLL - so the class does not exist - in that case because compilation fails)

```
C:\projects\zephir\ext\test\testinterface.zep.c : fatal error C1083: Cannot open compiler generated file: 'Release_TS\projects\zephir\ext\test\testinterface.zep.obj': No such file or directory
```

which hints that compilation fails ^^

**Comment by umermalik129** [comment]
To test the code after changing I have to create PR or there is other way? I don't want to setup own CI server

**Comment by steffengy** [comment]
@umermalik129 
you could try to compile the zephir test extension yourself (appveyor.yml should hint at that)
any commit you add to the PR (push to your winfix branch) also gets automatically tested by the CI.

**Comment by umermalik129** [comment]
@steffengy I reverted `processAddSources` related changes and now the build is successful 

I think we only need to change the paths that will go inside release directory

**Comment by umermalik129** [comment]
@steffengy will it work?

**Comment by steffengy** [comment]
yeah sure tests work, but static builds are broken, just as before, without patching the configure script.

**Comment by umermalik129** [comment]
You mean Travis CI? appveyor builds successfully and I think it is related to windows build

**Comment by steffengy** [comment]
No I mean by reverting the changes you did you effectively get appveyor to work, but
break in case of #1202.
Anyways the current state in master works in all cases I'm aware of,
and you really shouldn't waste your time in fixing something that isn't broken,
atleast if not being done systematically.

**Pull request closed without merging**
