### PR TITLE
#203 - Add support syntax `passing variables by reference`

### PR DESCRIPTION
**Pull request by JellyBrick**
Hello!

* Type: new feature
* Link to issue: #203

In raising this pull request, I confirm the following:

- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I updated the CHANGELOG

Small description of the change:

- Add support for `passing variables by reference`

https://github.com/zephir-lang/zephir/issues/609#issuecomment-636311672

Thanks

### CODE REVIEW

**Comment by Jeckerson** [comment]
Hello! Could you add some tests?

**Comment by Jeckerson** [comment]
@JellyBrick Hi, any news or ETA on that?

**Comment by JellyBrick** [comment]
## TODO

- [ ] Add support syntax `typed reference` (like `int&`)

**Comment by Jeckerson** [comment]
@JellyBrick Could you implement that or prefer to pass for us?

**Comment by JellyBrick** [comment]
@Jeckerson 
> prefer to pass for us?

:ok_hand:

**Comment by JellyBrick** [comment]
@Jeckerson Should I add a test for `typed reference`?

**Comment by Jeckerson** [comment]
@JellyBrick Yes please. Also, as this PR is not implements full support of references, I'll create new separate branch `references` and this PR will be merged there. To make it easy to track process of this feature, because we still need to decide if it will be in `v0.13.x` or in `v0.14.x`.

**Review by Jeckerson — APPROVED** [review]

**Pull request merged**
