### PR TITLE
Implement symbol tables

### PR DESCRIPTION
**Pull request by sjinks**
See #1403 

@Jurigag could you please take a look? Is this what you wanted?

### CODE REVIEW

**Comment by Jurigag** [comment]
Im guessing, tomorrow i will check this on phalcon if it will work too. Also is there any test for this? Cuz don't sure.

**Comment by sjinks** [comment]
Yes, `test/requires.zep`. It created a symtable but only for PHP 5. I removed PHP 5 check, the test still passes.

**Comment by sergeyklay** [comment]
Looks like something went wrong. At least for PHP 7.1 (ZTS): https://travis-ci.org/phalcon/cphalcon/jobs/220252922#L1882

**Comment by sergeyklay** [comment]
Note: when you run tests separately there is no problem

```
$ vendor/bin/codecept run -vvv tests/unit/Mvc/ViewTest.php
Codeception PHP Testing Framework v2.2.10
Powered by PHPUnit 4.8.35 by Sebastian Bergmann and contributors.

Unit Tests (24) ------------------------------------------------------------
Modules: Db, Asserts, Phalcon, Filesystem, \Helper\Unit
----------------------------------------------------------------------------
✔ ViewTest: Get active render path (0.05s)
✔ ViewTest: Get current render level (0.01s)
✔ ViewTest: Get registered engines (0.00s)
✔ ViewTest: Mustache engine (0.07s)
✔ ViewTest: Twig engine (0.25s)
✔ ViewTest: Mustache mixed engine (0.00s)
✔ ViewTest: Twig mixed engine (0.01s)
✔ ViewTest: Mustache mixed engine partials (0.01s)
✔ ViewTest: Twig mixed engine partials (0.01s)
✔ ViewTest: Override layout (0.00s)
✔ ViewTest: Layout and pick (0.00s)
✔ ViewTest: Missing partial (0.01s)
✔ ViewTest: Exists (0.00s)
✔ ViewTest: Standard render (0.02s)
✔ ViewTest: Override main view (0.00s)
✔ ViewTest: Rendering with partials (0.02s)
✔ ViewTest: Get render (0.01s)
✔ ViewTest: Setters and getters (0.00s)
✔ ViewTest: View param isset (0.00s)
✔ ViewTest: Disable levels (0.02s)
✔ ViewTest: Cache di (1.02s)
✔ ViewTest: View cache independency (0.01s)
✔ ViewTest: View options (1.01s)
✔ ViewTest: Issue12648 (0.01s)
----------------------------------------------------------------------------


Time: 5.09 seconds, Memory: 8.00MB
```

```
$ php -v
PHP 7.1.3 (cli) (built: Apr  9 2017 13:09:23) ( ZTS DEBUG )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3, Copyright (c) 1999-2017, by Zend Technologies
```

**Pull request merged**
