### PR TITLE
fix #1025

### LINKED ISSUE #1025: DocBlock and get/set shortcuts
When documenting a property that uses a get/set shortcut the docBlock of the property is carried over to the get/set method.

```
class Example {
    /**
     * A property
     * 
     * @var boolean
     */
    protected _property = false { set };
}
```
is compiled to 
````
/**
 * A property
 *
 * @var boolean
 */
PHP_METHOD(Example, setProperty) {

    zval *property;

    zephir_fetch_params(0, 1, 0, &type);

    zephir_update_property_this(this_ptr, SL("_property"), type TSRMLS_CC);

}
````

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/24015911-docblock-and-get-set-shortcuts?utm_campaign=plugin&utm_content=tracker%2F280146&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F280146&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by KorsaR-ZN**

### CODE REVIEW

**Comment by ovr** [comment]
@KorsaR-ZN 
Can you please fix the PSR2 errors?
https://travis-ci.org/phalcon/zephir/jobs/73762830#L2694

**Comment by KorsaR-ZN** [comment]
@ovr, Yes, one minute

**Comment by KorsaR-ZN** [comment]
@ovr maybe need rebase?

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
