### PR TITLE
Re fix #1961

### LINKED ISSUE #1961: BUG: zephir_get_global
> Close all extensions compiled by zephir, including the phaclon extension. Leave only the test extension.

test/globals/server.zep
```
namespace Test\Globals;

class Server
{
    public function f1() -> void
    {
        echo _SERVER["PHP_SELF"];
        this->f2();
        echo _SERVER["PHP_SELF"];
    }
    
    public function f2() -> void
    {
        echo _SERVER["SCRIPT_NAME"];
    }
}
```
manual.php
```
$t = new Test\Globals\Server();
$t->f1();
```

output:
```
/php-src/php-7.2/Zend/zend_hash.c(1968) : ht=0x107e65720 is already destroyed
Assertion failed: (0), function _zend_is_inconsistent, file /php-src/php-7.2/Zend/zend_hash.c, line 64.
```

### PR DESCRIPTION
**Pull request by dreamsxin**
Hello!

* Type: bug fix
* Link to issue: https://github.com/phalcon/zephir/pull/1961

@sergeyklay Please help test again.

### CODE REVIEW

**Comment by dreamsxin** [comment]
Travis error log , I can't see.

**Comment by dreamsxin** [comment]
zephir_array_update_zval are separated it.

**Comment by sergeyklay** [comment]
@dreamsxin Good catch 👍

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you!

**Pull request merged**
