### PR TITLE
Activate code coverage with scrutinizer-ci

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by Green-Cat** [comment]
Major :+1:

**Comment by fezfez** [comment]
@andresgutierrez @steffengy : Any chance to merge this PR ? :beers:

**Comment by steffengy** [comment]
@fezfez 
Thanks for your effort, but I think that currently does not much, since scrutinizer does not seem enabled for the development branch, or am I misreading that?

**Comment by fezfez** [comment]
@steffengy : First you have to activate the coverage in you scrutinizer config (https://scrutinizer-ci.com/docs/tools/external-code-coverage/#changes-in-scrutinizer-configuration) but i think if the total configuration (scrutinizer config + send coverage) is not in master scrutinizer will not show coverage.

**Pull request merged**
