### PR TITLE
Fix #1818

### LINKED ISSUE #1818: Objects are not traversable with foreach
Presently, the only way to iterate over an object is with the PHP userland method `get_object_vars()`. 
I believe [this check](https://github.com/phalcon/zephir/blob/0a5dcb6b00fdf4ae267f676d580a3ac3d4ccc339/kernels/ZendEngine3/main.c#L35) should consider whether the parameter inherits `ArrayAccess` or any other classes that inherit `Traversable`

### PR DESCRIPTION
**Pull request by dreamsxin**
Hello! 

* Type: bug 
* Link to issue: #1818 #1595

In raising this pull request, I confirm the following:

- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [ ] I updated the CHANGELOG

Small description of change:

Iterator can't use reverse.

Thanks

### CODE REVIEW

**Comment by dreamsxin** [comment]
@sergeyklay Check

**Review by sergeyklay — APPROVED** [review]
Looks good to me!

**Comment by dreamsxin** [comment]
@sergeyklay Change a little bit of code, be smarter.

```zephir
class App
{
	public function test()
	{
		var k, v;
		var arr;

		let arr = [];
		for k, v in arr {
			echo k, v, "\n";
		}
	}
}
```
or
```zephir
class App
{
	public function test()
	{
		var k, v;
		var arr;

		let arr = new Arr();
		for k, v in arr {
			echo k, v, "\n";
		}
	}
}
```

**Comment by dreamsxin** [comment]
@sergeyklay It's difficult to make accurate judgments through possibleValue.

**Pull request merged**
