### PR TITLE
Optimizing memory

### PR DESCRIPTION
**Pull request by dreamsxin**
Hello!

* Type: code quality
* Link to issue:

In raising this pull request, I confirm the following:

- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I updated the CHANGELOG

Small description of change:

Thanks

### CODE REVIEW

**Comment by dreamsxin** [comment]
After
Zephir code:
```zephir
namespace Mytest;

class App
{
	public function fibonacci(int  n) -> int {
		if (n == 1 ||  n == 0){
			return n;
		}

		return  this->fibonacci(n - 1) + this->fibonacci(n - 2);
	}

	internal function _fibonacci(long n) {
		if (n == 1 ||  n == 0){
			return n;
		}

		return  this->_fibonacci(n - 1) + this->_fibonacci(n - 2);
	}

	public function fibonacci2(int n){
		this->_fibonacci(n);
	}
}
```
Test code
```php
function getMillisecond() {
    list($t1, $t2) = explode(' ', microtime());
    return (float)sprintf('%.0f',(floatval($t1)+floatval($t2))*1000);
}

class Test {
	function fibonacci($n)
	{
		if ($n == 1 or $n == 0) {
			return $n;
		}
		return $this->fibonacci($n - 1) + $this->fibonacci($n - 2);
	}
}
$test = new Test;
$startTime = getMillisecond();
$v = $test->fibonacci(30);
$endTime = getMillisecond();
echo 'PHP      '.($endTime - $startTime).PHP_EOL;

$app = new \Mytest\App;
$startTime = getMillisecond();
$app->fibonacci(30);
$endTime = getMillisecond();
echo 'Zephir   '.($endTime - $startTime).PHP_EOL;

$startTime = getMillisecond();
$app->fibonacci2(30);
$endTime = getMillisecond();
echo 'internal '.($endTime - $startTime).PHP_EOL;
```
Before optimization
```text
PHP      320
Zephir   1333
internal 880
```

After optimization
```text
PHP      324
Zephir   803
internal 400
```

**Comment by ruudboon** [comment]
Sweet!

**Comment by niden** [comment]
@dreamsxin If you have not already, can you check `internal` in Windows build? I remember the last time I used `internal` the Windows build (appveyor) was failing.

**Comment by dreamsxin** [comment]
@niden What error, It's show AppVeyor build succeeded.

**Comment by niden** [comment]
@dreamsxin This was a few months ago when I used `internal` I do not have the build URL unfortunately. I will however try the `internal` again and will let you know. 

Thanks bud.

**Pull request merged**
