### PR TITLE
Add magic shortcuts: 'is', 'add'

### PR DESCRIPTION
**Pull request by mruz**
``` zep
class Person {

  protected name { set, get  };
  protected age { set, get };
  protected male = true { set, is };
  protected phone { add, get };
  protected email { add, get };
}
```

``` php
$person = new Person;
$person->setName('Julia');
$person->setAge(21);
$person->setMale(false);

$person
    ->addPhone('0123456789')
    ->addEmail('julia@example.com');

echo 'Name: ' . $person->getName() .
     'Age: ' . $person->getAge() .
     'Sex: ' . ($person->isMale() ? 'Male' : 'Female') .
     'Phone: ' . $person->getPhone() .
     'Email: ' . $person->getEmail();
```

### CODE REVIEW

**Comment by mruz** [comment]
@steffengy what do you think about this? Refs https://github.com/phalcon/zephir/issues/417

**Comment by sergeyklay** [comment]
Refs https://github.com/phalcon/zephir/issues/1121

**Comment by mruz** [comment]
@andresgutierrez what do you think about it?

**Comment by Jurigag** [comment]
Why exactly this is still not merged ?

**Comment by Jurigag** [comment]
@andresgutierrez @sergeyklay Well asking above question again i guess.

**Comment by sergeyklay** [comment]
@Jurigag https://github.com/phalcon/zephir/issues/1121#issuecomment-154507884

**Comment by Jurigag** [comment]
Yea but **THIS IS PR**, not issue meaning implemented by @mruz, so why not merge it?

**Comment by sergeyklay** [comment]
Because there are no enough quorum

**Comment by Jurigag** [comment]
Oh, okay.

**Comment by steffengy** [comment]
also the implementation of adding `is` as alias for `get` is quite strange.
`is` should always explicitly return a boolean.

Before merging this we should also come to a consensus
on what "magic shortcuts" we want.

I do not want several hundreds of them, but do not see an issue with adding
those reducing boilerplate.

These uncertainties in terms of the design are the main reason
this is still not merged (and also the reason why this should not be merged
until these are resolved).

**Comment by mruz** [comment]
Originally there was only `add` "magic shortcuts" in this PR.
I asked about difference between `is` and `get` https://github.com/phalcon/zephir/issues/1121#issuecomment-177171607 @sergeyklay just said:
> better than

so I just created an alias to `get`. I didn't know about uncertainties, I'll push a new implementation for `is`.

**Comment by mruz** [comment]
@steffengy do we need to use backend->fetchProperty for returning bool in `is` shortcut? https://github.com/mruz/zephir/blob/e94c202b9a690234d6d4dbdceb919bb066123eb8/Library/Statements/ReturnStatement.php#L73

**Comment by steffengy** [comment]
@mruz depends if the generated code is different for ZE3.
since it currently isn't in any backend-specific class, I guess it's not.

**Comment by mruz** [comment]
@steffengy how about this implementation for the `is`?

**Comment by sergeyklay** [comment]
Cc: @phalcon/zephir-team

**Comment by flyingangel** [comment]
Good idea. 
But "add" does the same as "set" so there is no use
"is" should only return a boolean not a value : return (bool)[prop] === true
@sergeyklay

**Comment by mruz** [comment]
When I created it, `set` did not return anything, so I added `add`, `is` should return bool https://github.com/phalcon/zephir/pull/1174/files#diff-6831a39c4308ea680610729532fc6bb7R43.

**Comment by mruz** [comment]
@sergeyklay I can't rebuild failed build https://travis-ci.org/phalcon/zephir/builds/425215861?utm_source=github_status&utm_medium=notification, could you? or do we still need that PR?

**Comment by sergeyklay** [comment]
@mruz Could you please submit this PR to the 0.10.x branch? Also could you please squash commits into one to keep history clean.

**Pull request closed without merging**
