### PR TITLE
Fix #1775

### LINKED ISSUE #1775: Segmentation Fault: Manipulating an undefined variable as an array
When running PHP as CLI `$_SESSION` is undefined. So attempting to call this function will attempt to append an array element to an undefined variable which results in a segmentation fault.

```zep
function set(string index, var value)
{
    var uniqueId;

    let uniqueId = this->_uniqueId;
    if !empty uniqueId {
        let _SESSION[uniqueId . "#" . index] = value;
        return;
    }

    let _SESSION[index] = value;
}

set("test"); // segfault
```

Thanks :)

### PR DESCRIPTION
**Pull request by dreamsxin**
This PR generate tmp array and add to `&EG(symbol_table)`.

### CODE REVIEW

**Comment by dreamsxin** [comment]
@sergeyklay It's ok.

**Comment by sergeyklay** [comment]
@dreamsxin Segmentation fault (core dumped) on Travis for all PHP 7.x versions. Did you see

**Comment by dreamsxin** [comment]
@sergeyklay Check

**Review by sergeyklay — APPROVED** [review]

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
