### PR TITLE
Bug 1831

### PR DESCRIPTION
**Pull request by dreamsxin**
Hello!

* Type: bug fix
* Link to issue: #1831 

In raising this pull request, I confirm the following:

- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [ ] I updated the CHANGELOG

Small description of change:

Thanks

### CODE REVIEW

**Comment by dreamsxin** [comment]
@sergeyklay Please help check

**Review by sergeyklay — APPROVED** [review]
Looks good to me

**Comment by dschissler** [comment]
Man I wish that I knew how to do all the `Z_` stuff.

**Comment by dreamsxin** [comment]
@dschissler 
Can see 
https://docs.zephir-lang.com/0.11/en/welcome
and 
https://docs.zephir-lang.com/0.11/en/installation

Install
```shell
git clone https://github.com/phalcon/php-zephir-parser.git
cd php-zephir-parser
phpize
./configure
make
sudo make install

git clone https://github.com/phalcon/zephir
cd zephir
composer install
```

**Comment by dschissler** [comment]
@dreamsxin I was making a fluff comment that I want to learn how to write the C some day.  I already do quite a lot of .zep programming.  I'm learning Rust now so I'll come back around to C someday.

**Comment by dreamsxin** [comment]
You can see http://php.net/manual/en/internals2.ze1.zendapi.php
And Google search.

**Comment by dschissler** [comment]
Thanks, that is a good one.  There is also a good PHP extension in Rust article somewhere.  I think that Rust is a good fit because I can use it for WASM, PHP extensions and it will be growing a lot over the next several years.  I will learn PHP extensions using Rust and then later I should be able to read all of the C code for Zephir and that only the boilerplate will be different.

**Pull request merged**
