### PR TITLE
The json-c is not needed anymore

### PR DESCRIPTION
**Pull request by sergeyklay**

### CODE REVIEW

**Comment by sergeyklay** [comment]
@steffengy Can you please review?

**Comment by steffengy** [comment]
Thanks

**Comment by kylekatarnls** [comment]
Hi, Do the doc shouldn't be updated: http://docs.zephir-lang.com/en/latest/install.html

**Comment by sergeyklay** [comment]
https://github.com/phalcon/zephir-docs/pull/39

**Pull request merged**
