### PR TITLE
Composer >= 5.4

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by ovr** [comment]
@steffengy

**Comment by sergeyklay** [comment]
`master`? Phalcon `2.0.x` no longer will be compiled with new Zephir versions?

**Comment by steffengy** [comment]
@sergeyklay 
I talked with @andresgutierrez about that, and he also was sharing my
opionion that anyone using PHP 5.3 is pretty much reckless (many security issues and no EOL since more than a year).

I guess that either means that phalcon is also dropping PHP5.3 or that it
might be (as I mentioned several times) make sense to use tagged releases
instead of the master branch for phalcon.

**Comment by hylent** [comment]
It's time to support Trait :smiley:

**Pull request merged**
