### PR TITLE
Updated kernel require

### PR DESCRIPTION
**Pull request by dreamsxin**
Hello!

* Type: bug fix | code quality

In raising this pull request, I confirm the following:

- [x] I have checked that another pull request for this purpose does not exist

Does `ob_clean` needs to be replaced with `ob_start`?

```zep
class External3
{
	protected someVariable;

	public function req(var path, var requires) -> void
	{
		ob_clean(); // <-- This postion
		require path;
		requires->setContent(ob_get_contents());
	}
}
```

### CODE REVIEW

**Comment by sergeyklay** [comment]
As a far as I remember ob_clean() is needed because there is output buffered by phpunit. Anyway try to replace it by ob_start() and let's see what happens?

**Comment by sergeyklay** [comment]
@dreamsxin Could you please fix this:
```diff
diff --git a/Library/CompilerFile.php b/Library/CompilerFile.php
index 05ffa8ce..2a947bfd 100644
--- a/Library/CompilerFile.php
+++ b/Library/CompilerFile.php
@@ -973,7 +973,7 @@ final class CompilerFile implements FileInterface
         }
 
         if (\count($this->headerCBlocks) > 0) {
-            $code .= implode($this->headerCBlocks, PHP_EOL).PHP_EOL;
+            $code .= implode(PHP_EOL, $this->headerCBlocks).PHP_EOL;
         }
 
         /*
```

**Comment by dreamsxin** [comment]
@sergeyklay OK

**Comment by sergeyklay** [comment]
Oh! There is yet another deprecation:

```diff
diff --git a/templates/Api/themes/zephir/partials/class/method-summary.phtml b/templates/Api/themes/zephir/partials/class/method-summary.phtml
index 858c5619..b668da5c 100644
--- a/templates/Api/themes/zephir/partials/class/method-summary.phtml
+++ b/templates/Api/themes/zephir/partials/class/method-summary.phtml
@@ -1,28 +1,27 @@
 <?php
 
 $allTypes = [];
 $_lClasses = $method->getReturnClassTypes();
 
 foreach ($_lClasses as $c) {
-    if ($c{0} == "\\") {
-        $allTypes[] = substr($c,1);
+    if ('\\' == $c[0]) {
+        $allTypes[] = substr($c, 1);
     } else {

```

**Comment by dreamsxin** [comment]
@sergeyklay "Deprecated: Directive 'allow_url_include' is deprecated in Unknown on line 0"

**Comment by dreamsxin** [comment]
```txt
Unsilenced deprecation notices (112)
  112x: Function ReflectionType::__toString() is deprecated
    92x in PregMatchOptimizerTest::setUp from Zephir\Test\Optimizers\FunctionCall
    20x in HardDiskTest::shouldCatchErrorException from Zephir\Test\FileSystem
```

**Review by sergeyklay — APPROVED** [review]
:heart:

**Pull request merged**
