### PR TITLE
Fix #1400

### LINKED ISSUE #1400: ArrayAccess doesn't work in zephir-land
Not sure if fetch keyword supports ArrayAccess interface. Doesn't seems so, check this PR for more https://github.com/phalcon/cphalcon/pull/12670

It could be nice to implement it imho.

### PR DESCRIPTION
**Pull request by dreamsxin**
* Type: bug fix
* Link to issue: #1400 

In raising this pull request, I confirm the following:

- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [ ] I updated the CHANGELOG

Small description of change:

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
@dreamsxin This code seems to be incompatible with the Windows compiler. At least we have the following:

```
concat.c
C:\projects\zephir\ext\kernel\array.c(98): error C2059: syntax error: '}'
C:\projects\zephir\ext\kernel\array.c(166): error C2059: syntax error: '}'
C:\projects\zephir\ext\kernel\array.c(167): error C2065: 'offset': undeclared identifier
C:\projects\zephir\ext\kernel\array.c(169): error C2065: 'offset': undeclared identifier
C:\projects\zephir\ext\kernel\array.c(170): error C2065: 'offset': undeclared identifier
C:\projects\zephir\ext\kernel\array.c(170): warning C4133: 'function': incompatible types - from 'int *' to 'zval *'
C:\projects\zephir\ext\kernel\array.c(172): error C2065: 'offset': undeclared identifier
C:\projects\zephir\ext\kernel\array.c(167): warning C4133: 'initializing': incompatible types - from 'int *' to 'zval *'
C:\projects\zephir\ext\kernel\array.c(169): warning C4133: 'initializing': incompatible types - from 'int *' to 'zval *'
C:\projects\zephir\ext\kernel\array.c(172): warning C4133: 'initializing': incompatible types - from 'int *' to 'zval *'
C:\projects\zephir\ext\kernel\array.c(204): error C2059: syntax error: '}'
C:\projects\zephir\ext\kernel\array.c(205): error C2065: 'offset': undeclared identifier
C:\projects\zephir\ext\kernel\array.c(207): error C2065: 'offset': undeclared identifier
C:\projects\zephir\ext\kernel\array.c(209): error C2065: 'offset': undeclared identifier
C:\projects\zephir\ext\kernel\array.c(205): warning C4133: 'initializing': incompatible types - from 'int *' to 'zval *'
C:\projects\zephir\ext\kernel\array.c(207): warning C4133: 'initializing': incompatible types - from 'int *' to 'zval *'
C:\projects\zephir\ext\kernel\array.c(209): warning C4133: 'initializing': incompatible types - from 'int *' to 'zval *'
C:\projects\zephir\ext\kernel\array.c(245): error C2059: syntax error: '}'
C:\projects\zephir\ext\kernel\array.c(286): error C2059: syntax error: '}'
C:\projects\zephir\ext\kernel\array.c(287): error C2065: 'offset': undeclared identifier
C:\projects\zephir\ext\kernel\array.c(289): error C2065: 'offset': undeclared identifier
C:\projects\zephir\ext\kernel\array.c(290): error C2065: 'offset': undeclared identifier
C:\projects\zephir\ext\kernel\array.c(290): warning C4133: 'function': incompatible types - from 'int *' to 'zval *'
C:\projects\zephir\ext\kernel\array.c(287): warning C4133: 'initializing': incompatible types - from 'int *' to 'zval *'
C:\projects\zephir\ext\kernel\array.c(289): warning C4133: 'initializing': incompatible types - from 'int *' to 'zval *'
C:\projects\zephir\ext\kernel\array.c(307): error C2059: syntax error: '}'
C:\projects\zephir\ext\kernel\array.c(308): error C2065: 'offset': undeclared identifier
C:\projects\zephir\ext\kernel\array.c(310): error C2065: 'offset': undeclared identifier
C:\projects\zephir\ext\kernel\array.c(308): warning C4133: 'initializing': incompatible types - from 'int *' to 'zval *'
C:\projects\zephir\ext\kernel\array.c(310): warning C4133: 'initializing': incompatible types - from 'int *' to 'zval *'
debug.c
```

I think this can be made more portable. Could you take a look? 
https://ci.appveyor.com/project/sergeyklay/zephir/builds/22545498/job/eqfm2ltqtgtcex0c?fullLog=true#L61

**Comment by dreamsxin** [comment]
PHP 5.x will be supported today.

**Comment by dreamsxin** [comment]
@sergeyklay All right

**Review by sergeyklay — APPROVED** [review]
Looks good to me!

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
