### PR TITLE
Fixed property visibility

### PR DESCRIPTION
**Pull request by sergeyklay**
Hello!

* Type: bug fix
* Link to issue: #2057, https://github.com/phalcon/cphalcon/issues/14810, https://github.com/phalcon/cphalcon/issues/14766

In raising this pull request, I confirm the following:

- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I updated the CHANGELOG

Small description of change: 

Zephir ignored property visibility and has not thrown error when setting   private/protected properties in scope that shouldn't intended for it.

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
@dreamsxin There are 4 _failed_ and 14 _passed_ tests. It seems I need help here. Could you please take a look what wrong with `zephir_update_property_zval`. For skipped tests see `unit-tests/Extension/Oo/Scopes/PrivateScopeTest.php`.

**Comment by sergeyklay** [comment]
@dreamsxin Do you have any idea?

**Comment by dreamsxin** [comment]
@sergeyklay Fatal error: Class 'TestScopePhp' not found

**Comment by sergeyklay** [comment]
@dreamsxin Try `composer dump-autoload` from the project root

**Comment by dreamsxin** [comment]
@sergeyklay 
Commented code
```c
	/* Use caller's scope */
	//zephir_set_scope(ce);

	/* Restore original scope */
	//zephir_set_scope(scope);
```
Will throw
```output
Fatal error: Uncaught Error: Cannot access private property TestScopeExtending::$privateProperty in /home/myleft/work/test.php:27
Stack trace:
#0 /home/myleft/work/test.php(27): Test\Oo\Scopes\AbstractClass->setProperty('privateProperty', 'test')
#1 {main}
  thrown in /home/myleft/work/test.php on line 27
```
You want to throw an exception with read

**Comment by dreamsxin** [comment]
Maybe can change 
`int zephir_update_property_zval(zval *object, const char *property_name, unsigned int property_length, zval *value)` to 
`int zephir_update_property_zval(zval *object, zend_class_entry current_ce, const char *property_name, unsigned int property_length, zval *value)`

Like:
```c
PHP_METHOD(Test_Oo_Scopes_AbstractClass, setProperty) {

	zephir_method_globals *ZEPHIR_METHOD_GLOBALS_PTR = NULL;
	zval *name_param = NULL, *value, value_sub;
	zval name;
	zval *this_ptr = getThis();

	ZVAL_UNDEF(&name);
	ZVAL_UNDEF(&value_sub);

	ZEPHIR_MM_GROW();
	zephir_fetch_params(1, 2, 0, &name_param, &value);

	zephir_get_strval(&name, name_param);


	zephir_update_property_zval_zval(this_ptr, test_oo_scopes_abstractclass_ce, &name, value);
	RETURN_THIS();

}
```

**Comment by sergeyklay** [comment]
@dreamsxin Yes, commenting does the trick. But if you run test without scope-related code you will see some failed tests. Do you suggest to modify `zephir_update_property_zval_zval` and to change scope inside `zephir_update_property_zval_zval` ?

**Comment by sergeyklay** [comment]
@dreamsxin It seems removing scope-related code works only for PHP < 7.4. Did you try 7.4?

**Comment by dreamsxin** [comment]
If you want the scope of the variable to work, have to modify it.
Changes may affect some of the previous code and need to be fully tested.
I don't recommend any changes.

Zephir's scope doesn't have to be exactly the same as PHP's

**Comment by dreamsxin** [comment]
@sergeyklay Test in 7.4
```php
        $tester = new Test\Oo\Scopes\PrivateScopeTester();
        $tester->setPropertyObj(new TestScopePhp(), 'privateProperty', 'test');
```
`Fatal error: Uncaught Error: Cannot access private property TestScopePhp::$privateProperty in /home/myleft/work/test.php:27`

**Comment by sergeyklay** [comment]
@dreamsxin Take a look at https://github.com/phalcon/zephir/compare/3bbdc7a...b534cf9 As you can see tests for PHP 7.4 failed.

**Comment by sergeyklay** [comment]
@dreamsxin Removing scope does not help :-/ Any idea?

**Comment by dreamsxin** [comment]
@sergeyklay I test in local
```php
<?php

class UserExample extends Test\Oo\PropertyAccess
{
}

$example = new UserExample();
$example->setPrivateVariable('test');

var_dump($example->getPrivateVariable());

class TestScopeExtending extends Test\Oo\Scopes\AbstractClass
{
    private $privateProperty = 'private';
    protected $protectedProperty = 'protected';
    public $publicProperty = 'public';

    /**
     * @return string
     */
    public function getProtectedProperty(): string
    {
        return $this->protectedProperty;
    }
}

$obj = new TestScopeExtending();
$obj->setProperty('privateProperty2', 'test');

var_dump($obj->getPrivateProperty2());


class TestScopeExtendingMagic extends Test\Oo\Scopes\AbstractClassMagic
{
    private $privateProperty2 = 'private';

    public function getProtectedProperty(): string
    {
        return $this->protectedProperty;
    }
}

$tester = new Test\Oo\Scopes\PrivateScopeTester();
$object = new TestScopeExtendingMagic();

$actual = $tester->setPropertyObj($object, 'privateProperty', 'test');
var_dump($actual);
var_dump($object->setCount);

$tester = new Test\Oo\Scopes\PrivateScopeTester();
$obj = $tester->setPropertyNew(TestScopeExtendingMagic::class, 'privateProperty', 'test');

var_dump($obj->privateProperty);
var_dump($obj->setCount);
```
```out
string(4) "test"
string(4) "test"
string(4) "test"
int(1)
string(4) "test"
int(1)
```
See https://github.com/phalcon/zephir/pull/2079

**Comment by sergeyklay** [comment]
@dreamsxin Aha! It seems we don't need to change scope for `zephir_read_property` too. Good catch. Thank you!

**Comment by sergeyklay** [comment]
@dreamsxin Removing scope-related code from `zephir_update_property_zval` as well as `zephir_read_property` works _only_ for PHP 7.4. I've added new test (see https://github.com/phalcon/zephir/pull/2078/commits/8da899ba166e2b31700b92000e3cd1b173af053c).

**Review by ruudboon — APPROVED** [review]
Great job!

**Comment by sergeyklay** [comment]
image

**Comment by dreamsxin** [comment]
@sergeyklay PHP < 7.4  Can't be modified, but no exception is thrown
```php

class TestScopeExtendingMagic
{
    private $privateProperty2 = 'private';

    public function getProtectedProperty(): string
    {
        return $this->protectedProperty;
    }

    public function getPrivateProperty2()
    {
        return $this->privateProperty2;
    }
}

class PrivateScopeTester 
{
    public function setPropertyObj($obj, $property, $value)
    {
        $obj->{$property} = $value;

        return $obj->{$property};
    }
}

$tester = new PrivateScopeTester();
$object = new TestScopeExtendingMagic();


$tester->setPropertyObj($object, 'privateProperty2', 'CHANGED');
var_dump($object->getPrivateProperty2());
```

**Comment by sergeyklay** [comment]
@dreamsxin Yes, see my comments here https://github.com/phalcon/zephir/pull/2078/commits/f41d57f9ce506a4125e8353c0e08bbfe28102f3f

Question: Can we modify this behavior so that Zephir will throw E_NOTICE for PHP 7.0 - 7.3 ?

**Comment by Jurigag** [comment]
Wow great job guys that you fixed this finally. It was really keeping me from updating to 4.0 and suggest it anywhere.

**Comment by sergeyklay** [comment]
@dreamsxin 

```php
class PrivateScopeTester
{
    public function setPropertyObj($obj, string $property, $value)
    {
        $obj->{$property} = $value;
    }
}

class TestScopePhpMagic
{
    public function __set($name, $value)
    {
        $this->$name = $value;
    }
}

class TestScopePhpMagicExtending extends TestScopePhpMagic
{
    private $privateProperty2 = 'private2';
}

$obj = new TestScopePhpMagicExtending();
var_dump($obj);

$tester = new PrivateScopeTester();
$tester->setPropertyObj($obj, 'privateProperty2', 'CHANGED');
var_dump($obj);
```

```
object(TestScopePhpMagicExtending)#1 (5) {
  ["privateProperty2":"TestScopePhpMagicExtending":private]=>
  string(8) "private2"
}
object(TestScopePhpMagicExtending)#1 (1) {
  ["privateProperty2":"TestScopePhpMagicExtending":private]=>
  string(8) "private2"
}
```

PHP 7.0.33

Property is not changed. But there is no notice/error.

**Pull request merged**
