### PR TITLE
Php8

### PR DESCRIPTION
**Pull request by dreamsxin**
Hello!

* Type: bug fix
* Link to issue: #2111 

In raising this pull request, I confirm the following:

- [ ] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I updated the CHANGELOG

Small description of change:

Thanks

### CODE REVIEW

**Comment by Jeckerson** [comment]
Gives seg fault. Strange why last commit didn't triggered all actions =\

**Comment by Jeckerson** [comment]
Seg fault is in `zephir_fcall_self` case. `zephir_fcall_parent` seems to be ok.

**Comment by Jeckerson** [comment]
Zephir code:
```
public static function callParentFunction() -> string
{
    return parent::getCalledClass();
}
```

Before:
```
RuntimeException: Call to undefined method parent::getcalledclass()
```

After this PR:
```
Error: Call to undefined method Stub\Oo\ConcreteStatic::callParentFunction()
```

**Comment by dreamsxin** [comment]
@Jeckerson 

How to test, I need to reproduce the error
```php
var_dump(Stub\Oo\ConcreteStatic::callParentFunction());
```
```zep
namespace Stub\Oo;

class ConcreteStatic extends AbstractStatic
{
	public static function parentFunction()
	{
		return __METHOD__;
	}

	public static function childFunction()
	{
		return self::parentFunction();
	}

	public static function simpleStaticIntReturn() -> int
	{
	    return 1337;
	}

	public static function callParentFunction() -> string
	{
	    return parent::getCalledClass();
	}
}
```

**Comment by Jeckerson** [comment]
@dreamsxin Rebase from `phalcon:zephir-php8`. There are latest changes that your fork doesn't contain.

**Comment by dreamsxin** [comment]
PHP 8.0.1 (cli) (built: Jan 13 2021 08:22:35) ( NTS )

**Comment by Jeckerson** [comment]
@dreamsxin Your fork do not have latest CI actions, you could look from CI fails.

**Comment by Jeckerson** [comment]
@dreamsxin Also, you could run inside docker container

https://github.com/phalcon/zephir/blob/development/docker/8.0/Dockerfile

```
docker-compose up -d
docker exec -it phalcon-zephir-8.0 bash
cd /opt && /srv/.ci/install-zephir-parser.sh
cd /srv
php zephir stubs
cd ext/ && ./install
cd .. && .ci/run-tests.sh
```

**Comment by dreamsxin** [comment]
@Jeckerson Test again, 
```c
			if (Z_TYPE_P(func) == IS_STRING) {
				fcic->function_handler = zend_hash_find_ptr(&calling_scope->parent->function_table, Z_STR_P(func));
			}
```

**Comment by dreamsxin** [comment]
In PHP8，
```php
 $test = new Scall();
echo $test::testCallStatic(); // out: hello ScallParent
```

**Comment by dreamsxin** [comment]
@Jeckerson Check https://github.com/dreamsxin/zephir/runs/1814671283?check_suite_focus=true

**Comment by Jeckerson** [comment]
@dreamsxin Nice!

```
$test = new Scall();
echo $test::testCallStatic(); // out: hello ScallParent
```
Is it a bug or new behavior of PHP8 ?

**Comment by Jeckerson** [comment]
image

https://github.com/dreamsxin/zephir/runs/1814671257?check_suite_focus=true

On 7.4 gives seg fault :(

**Review by AlexNDRmac — APPROVED** [review]

**Review by Jeckerson — APPROVED** [review]

**Pull request merged**
